# Generated by Django 3.2.4 on 2021-06-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientuser',
            old_name='avator',
            new_name='avatar',
        ),
    ]
