# Generated by Django 3.2.4 on 2021-06-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
